export const data = [
  {
    id: 1,
    Title: "The Silent Patient",
    Author: "Alex Michaelides",
    Genre: "Psychological Thriller",
    Price: 25.0,
    Country: "United States",
    img: "img/book5.jpg",
  },
  {
    id: 2,
    Title: "Educated",
    Author: "Tara Westover",
    Genre: "Memoir",
    Price: 18.99,
    Country: "United States",
    img: "img/book3.jpg",
  },
  {
    id: 3,
    Title: "Sapiens: A Brief History of Humankind",
    Author: "Yuval Noah Harari",
    Genre: "Non-Fiction",
    Price: 19.99,
    Country: "Israel",
    img: "img/book9.jpg",
  },
  {
    id: 4,
    Title: "Dune",
    Author: "Frank Herbert",
    Genre: "Science Fiction",
    Price: 15.5,
    Country: "United States",
    img: "img/book.jpg",
  },
  {
    id: 5,
    Title: "To Kill a Mockingbird",
    Author: "Harper Lee",
    Genre: "Fiction",
    Price: 14.99,
    Country: "United States",
    img: "img/book7.jpg",
  },
  {
    id: 6,
    Title: "To Kill a Mockingbird",
    Author: "Harper Lee",
    Genre: "Fiction",
    Price: 12.99,
    Country: "United States",
    img: "img/book6.jpg",
  },
  {
    id: 7,
    Title: "Dune",
    Author: "Frank Herbert",
    Genre: "Science Fiction",
    Price: 18.5,
    Country: "United States",
    img: "img/book2.jpg",
  },
  {
    id: 8,
    Title: "Educated",
    Author: "Tara Westover",
    Genre: "Memoir",
    Price: 14.95,
    Country: "United States",
    img: "img/book5.jpg",
  },
  {
    id: 9,
    Title: "The Da Vinci Code",
    Author: "Dan Brown",
    Genre: "Mystery/Thriller",
    Price: 10.99,
    Country: "United States",
    img: "img/book4.jpg",
  },
  {
    id: 10,
    Title: "Sapiens: A Brief History of Humankind",
    Author: "Yuval Noah Harari",
    Genre: "Non-Fiction",
    Price: 20.0,
    Country: "United Kingdom",
    img: "img/book3.jpg",
  },
  {
    id: 11,
    Title: "The Great Gatsby",
    Author: "F. Scott Fitzgerald",
    Genre: "Fiction",
    Price: 9.99,
    Country: "United States",
    img: "img/book.jpg",
  },
];
